FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY index.html ./
COPY style.css ./
COPY script.js ./
COPY manifest.json ./
COPY service-worker.js ./
COPY LICENSE ./
COPY data ./data
COPY imagens ./imagens
COPY sons ./sons
RUN sed -i 's#/usr/share/nginx/html#/usr/share/nginx/html#g' /etc/nginx/conf.d/default.conf || true
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
